# Generated by Django 4.0.4 on 2022-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_service', '0005_remove_client_zip_code_remove_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='date_of_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of service request completed'),
        ),
    ]
