# Generated by Django 4.0.4 on 2022-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_service', '0002_alter_client_zip_code_alter_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
