# Generated by Django 4.0.4 on 2022-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_service', '0004_remove_client_firm_nip_regon_remove_client_firm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ZIP_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street_number',
        ),
        migrations.AddField(
            model_name='service_request',
            name='ZIP_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='service_request',
            name='city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='service_request',
            name='street_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
