# Generated by Django 4.0.4 on 2022-06-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_service', '0009_alter_hardware_fault_repair_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
